DROP TABLE IDENTITIES.IDENTITIES;
CREATE TABLE IDENTITIES.IDENTITIES (
    IDENTITIES_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT IDENTITY_PK PRIMARY KEY,
    IDENTITIES_UID varchar(50),
    IDENTITIES_DISPLAYNAME varchar(50),
    IDENTITIES_EMAIL varchar(50),
    IDENTITIES_PASS varchar(50)
);
DROP TABLE IDENTITIES.ADDRESS;
CREATE TABLE IDENTITIES.ADDRESS(
    ADDRESS_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT ADDRESS_PK PRIMARY KEY,
    ADDRESS_STREET varchar(50),
    ADDRESS_CITY varchar(50),
    ADDRESS_COUNTRY varchar(50),
    ADDRESS_ZIPCODE varchar(50) 
);

